ingress:
  - hostname: tunnel.niuma.ru
    service: http://127.0.0.1:8088
  - hostname: niuma.ru
    service: http://127.0.0.1:8088
  - hostname: www.niuma.ru
    service: http://127.0.0.1:8088
  - service: http_status:404
